local M = {}

function M.apply(hi, c)
	hi("Normal", { fg = c.fg, bg = c.bg })
	hi("NormalFloat", { fg = c.fg, bg = c.bg_surface })
	hi("FloatBorder", { fg = c.bg_border, bg = c.bg_surface })
	hi("CursorLine", { bg = c.bg_surface })
	hi("CursorColumn", { bg = c.bg_surface })
	hi("ColorColumn", { bg = c.bg_surface })
	hi("Visual", { bg = c.bg_hl })
	hi("VisualNOS", { bg = c.bg_hl })
	hi("Search", { fg = c.bg, bg = c.yellow })
	hi("IncSearch", { fg = c.bg, bg = c.orange })
	hi("CurSearch", { fg = c.bg, bg = c.orange })
	hi("Substitute", { fg = c.bg, bg = c.orange })
	hi("LineNr", { fg = c.fg_muted })
	hi("CursorLineNr", { fg = c.orange, bold = true })
	hi("SignColumn", { fg = c.fg_muted, bg = c.bg })
	hi("FoldColumn", { fg = c.fg_muted, bg = c.bg })
	hi("Folded", { fg = c.fg_dim, bg = c.bg_surface })
	hi("VertSplit", { fg = c.bg_border })
	hi("WinSeparator", { fg = c.bg_border })
	hi("StatusLine", { fg = c.fg_dim, bg = c.bg_surface })
	hi("StatusLineNC", { fg = c.fg_muted, bg = c.bg_surface })
	hi("TabLine", { fg = c.fg_muted, bg = c.bg_surface })
	hi("TabLineFill", { bg = c.bg_surface })
	hi("TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
	hi("WinBar", { fg = c.fg_dim, bg = c.bg })
	hi("WinBarNC", { fg = c.fg_muted, bg = c.bg })
	hi("Pmenu", { fg = c.fg_dim, bg = c.bg_surface })
	hi("PmenuSel", { fg = c.fg, bg = c.bg_hl })
	hi("PmenuSbar", { bg = c.bg_border })
	hi("PmenuThumb", { bg = c.fg_muted })
	hi("WildMenu", { fg = c.bg, bg = c.orange })
	hi("Directory", { fg = c.teal })
	hi("Title", { fg = c.orange, bold = true })
	hi("MatchParen", { fg = c.orange, bold = true, underline = true })
	hi("NonText", { fg = c.bg_border })
	hi("SpecialKey", { fg = c.bg_border })
	hi("Whitespace", { fg = c.bg_border })
	hi("EndOfBuffer", { fg = c.bg })
	hi("Conceal", { fg = c.fg_muted })
	hi("QuickFixLine", { bg = c.bg_hl })
	hi("ModeMsg", { fg = c.fg_dim, bold = true })
	hi("MoreMsg", { fg = c.teal })
	hi("Question", { fg = c.teal })
	hi("ErrorMsg", { fg = c.red })
	hi("WarningMsg", { fg = c.yellow })
	hi("DiffAdd", { bg = "#1a3328" })
	hi("DiffChange", { bg = "#1a2a33" })
	hi("DiffDelete", { fg = c.red, bg = "#2a1a1a" })
	hi("DiffText", { bg = "#1e3545" })
	hi("SpellBad", { sp = c.red, undercurl = true })
	hi("SpellCap", { sp = c.yellow, undercurl = true })
	hi("SpellLocal", { sp = c.teal, undercurl = true })
	hi("SpellRare", { sp = c.purple, undercurl = true })
end

return M
