local M = {}

function M.apply(hi, c)
	hi("Comment", { fg = c.fg_muted, italic = true })
	hi("String", { fg = c.green })
	hi("Character", { fg = c.green })
	hi("Number", { fg = c.amber })
	hi("Float", { fg = c.amber })
	hi("Boolean", { fg = c.amber })
	hi("Identifier", { fg = c.fg })
	hi("Function", { fg = c.teal })
	hi("Statement", { fg = c.orange })
	hi("Conditional", { fg = c.orange })
	hi("Repeat", { fg = c.orange })
	hi("Label", { fg = c.orange })
	hi("Operator", { fg = c.fg_dim })
	hi("Keyword", { fg = c.orange })
	hi("Exception", { fg = c.red })
	hi("PreProc", { fg = c.pink })
	hi("Include", { fg = c.pink })
	hi("Define", { fg = c.pink })
	hi("Macro", { fg = c.pink })
	hi("PreCondit", { fg = c.pink })
	hi("Type", { fg = c.yellow })
	hi("StorageClass", { fg = c.purple })
	hi("Structure", { fg = c.yellow })
	hi("Typedef", { fg = c.yellow })
	hi("Special", { fg = c.amber })
	hi("SpecialChar", { fg = c.amber })
	hi("Tag", { fg = c.teal })
	hi("Delimiter", { fg = c.fg_dim })
	hi("SpecialComment", { fg = c.fg_muted, bold = true })
	hi("Debug", { fg = c.red })
	hi("Underlined", { underline = true })
	hi("Error", { fg = c.red })
	hi("Todo", { fg = c.bg, bg = c.yellow, bold = true })
end

return M
