local M = {}

function M.apply(hi, c)
	hi("@variable", { fg = c.fg })
	hi("@variable.builtin", { fg = c.pink })
	hi("@variable.parameter", { fg = c.fg_dim })
	hi("@variable.member", { fg = c.fg })
	hi("@constant", { fg = c.amber })
	hi("@constant.builtin", { fg = c.amber })
	hi("@constant.macro", { fg = c.amber })
	hi("@module", { fg = c.blue })
	hi("@label", { fg = c.orange })
	hi("@string", { fg = c.green })
	hi("@string.escape", { fg = c.amber })
	hi("@string.regexp", { fg = c.pink })
	hi("@character", { fg = c.green })
	hi("@number", { fg = c.amber })
	hi("@boolean", { fg = c.amber })
	hi("@float", { fg = c.amber })
	hi("@function", { fg = c.teal })
	hi("@function.builtin", { fg = c.teal, italic = true })
	hi("@function.call", { fg = c.teal })
	hi("@function.macro", { fg = c.pink })
	hi("@function.method", { fg = c.teal })
	hi("@function.method.call", { fg = c.teal })
	hi("@constructor", { fg = c.yellow })
	hi("@operator", { fg = c.fg_dim })
	hi("@keyword", { fg = c.orange })
	hi("@keyword.conditional", { fg = c.orange })
	hi("@keyword.repeat", { fg = c.orange })
	hi("@keyword.return", { fg = c.orange })
	hi("@keyword.exception", { fg = c.red })
	hi("@keyword.import", { fg = c.pink })
	hi("@keyword.operator", { fg = c.orange })
	hi("@keyword.function", { fg = c.orange })
	hi("@keyword.modifier", { fg = c.purple })
	hi("@type", { fg = c.yellow })
	hi("@type.builtin", { fg = c.yellow, italic = true })
	hi("@type.qualifier", { fg = c.orange })
	hi("@attribute", { fg = c.pink })
	hi("@property", { fg = c.fg })
	hi("@comment", { fg = c.fg_muted, italic = true })
	hi("@comment.todo", { fg = c.bg, bg = c.yellow, bold = true })
	hi("@comment.note", { fg = c.bg, bg = c.teal, bold = true })
	hi("@comment.warning", { fg = c.bg, bg = c.yellow, bold = true })
	hi("@comment.error", { fg = c.bg, bg = c.red, bold = true })
	hi("@punctuation.bracket", { fg = c.fg_dim })
	hi("@punctuation.delimiter", { fg = c.fg_dim })
	hi("@punctuation.special", { fg = c.amber })
	hi("@tag", { fg = c.orange })
	hi("@tag.attribute", { fg = c.teal })
	hi("@tag.delimiter", { fg = c.fg_muted })
	hi("@markup.heading", { fg = c.orange, bold = true })
	hi("@markup.strong", { bold = true })
	hi("@markup.italic", { italic = true })
	hi("@markup.strikethrough", { strikethrough = true })
	hi("@markup.link", { fg = c.teal, underline = true })
	hi("@markup.link.url", { fg = c.blue, underline = true })
	hi("@markup.raw", { fg = c.green })
	hi("@markup.list", { fg = c.orange })
end

return M
